apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: ENV
      valueFrom:
        configMapKeyRef:
          name: myconfig
          key: ENV
