- backend:
    serviceName: food-service
    servicePort: 8080
  path: /food
  pathType: ImplementationSpecific

- backend:
    serviceName: pay-service.critical-space
    servicePort: 8282
  path: /pay
  pathType: ImplementationSpecific


apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /watch
        pathType: Prefix
        backend:
          serviceName: video-service
          servicePort: 8080
      - path: /wear
        pathType: Prefix
        backend:
          serviceName: wear-service
          servicePort: 8080
